// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzjzwymguanwgjvzawav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6anp3eW1ndWFud2dqdnphd2F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMDM4NDgsImV4cCI6MjA1NjU3OTg0OH0.n9lLc4hhapuvb2Xqy1QMd1mYtQjf3-0uc3r5G1-CD54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);